"""initial schema

Revision ID: ddc25c9e8f36
Revises: 
Create Date: 2026-07-06 14:06:01.741633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REVIEWER', name='admin_role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.Enum('ADMIN', 'DEVICE', 'SYSTEM', name='actor_type', native_enum=False), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_uuid', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('operating_system', sa.String(length=255), nullable=False),
    sa.Column('agent_version', sa.String(length=50), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrollment_status', sa.Enum('ACTIVE', 'REVOKED', name='enrollment_status', native_enum=False), nullable=False),
    sa.Column('device_secret_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_uuid'), 'devices', ['device_uuid'], unique=True)
    op.create_table('elevation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_uuid', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('canonical_path', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('publisher', sa.String(length=500), nullable=True),
    sa.Column('signature_status', sa.Enum('UNSIGNED', 'TRUSTED', 'UNTRUSTED', 'HASH_MISMATCH', 'REVOKED', 'UNKNOWN', name='signature_status', native_enum=False), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_version', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'EXPIRED', name='elevation_request_status', native_enum=False), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elevation_requests_device_id'), 'elevation_requests', ['device_id'], unique=False)
    op.create_index(op.f('ix_elevation_requests_request_uuid'), 'elevation_requests', ['request_uuid'], unique=True)
    op.create_index(op.f('ix_elevation_requests_sha256'), 'elevation_requests', ['sha256'], unique=False)
    op.create_index(op.f('ix_elevation_requests_status'), 'elevation_requests', ['status'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elevation_request_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('EXECUTE', name='approval_action', native_enum=False), nullable=False),
    sa.Column('device_uuid', sa.UUID(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signature', sa.LargeBinary(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['elevation_request_id'], ['elevation_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce', name='uq_approvals_nonce')
    )
    op.create_index(op.f('ix_approvals_device_uuid'), 'approvals', ['device_uuid'], unique=False)
    op.create_index(op.f('ix_approvals_elevation_request_id'), 'approvals', ['elevation_request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_elevation_request_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_device_uuid'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_elevation_requests_status'), table_name='elevation_requests')
    op.drop_index(op.f('ix_elevation_requests_sha256'), table_name='elevation_requests')
    op.drop_index(op.f('ix_elevation_requests_request_uuid'), table_name='elevation_requests')
    op.drop_index(op.f('ix_elevation_requests_device_id'), table_name='elevation_requests')
    op.drop_table('elevation_requests')
    op.drop_index(op.f('ix_devices_device_uuid'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
